// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drqdqufckdzxufqcgbsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycWRxdWZja2R6eHVmcWNnYnNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODE5NDUsImV4cCI6MjA2NTU1Nzk0NX0.tUoLdZTZhra96KfqnFk0a-0UnO3m0FoyLn0zWtiX8eQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);